/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.ia.sdk.tools.module.cli

import io.ia.ignition.module.generator.ModuleGenerator
import io.ia.ignition.module.generator.api.GeneratorConfigBuilder
import java.io.File
import java.time.Duration
import java.time.Instant
import java.util.concurrent.Callable
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.HelpCommand
import picocli.CommandLine.Option

@Command(
        name = "ignition-module-gen",
        version = ["0.0.1"],
        description = ["Generates an Ignition module skeleton according to provided arguments."],
        subcommands = [HelpCommand::class],
        mixinStandardHelpOptions = true
)
class ModuleGeneratorCli : Callable<Int> {

    /**
     *
     */
    @Option(names = ["-s", "--scope"], interactive = true, description = ["Shorthand scope String like 'DCG'"])
    var scope: String? = null

    /**
     *
     */
    @Option(names = ["-d", "--directory"],
            description = ["Path to directory where new project should be created."], interactive = true)
    var directory: String? = null

    /**
     *
     */
    @Option(names = ["-n", "--name"], description = ["Spoken name of the module, not ending in 'module'"],
            interactive = true)
    var moduleName: String? = null

    /**
     * The java package qualification to use for the generated module.  For instance "org.mycompany.area"
     */
    @Option(names = ["-p", "--package"], description = ["'Base' package path for the module"], interactive = true)
    var packageRoot: String? = null

    @Option(names = ["--localDev"], description = ["Support 'local' plugin debugging."])
    var localDev = false

    private fun prompt(userPrompt: String): String {
        return System.console().readLine(userPrompt)
    }

    override fun call(): Int {

        println("""
                |** Ignition Module Generator **
                |Please provide some information so we can generate your skeleton module.
                |Press 'Enter' to use default if a default is stated as available.
                |"""
            .trimMargin("|")
        )

        when (scope) {
            null -> {
                scope = prompt("Enter scopes (any combination G, C or D. Example - GD): ")
            }
        }

        when (directory) {
            null -> {
                val input = prompt("Directory in which to make new project (default: current directory): ")

                directory = if (input.isNotEmpty()) {
                    input
                } else {
                    val currentDir = File("").absolutePath
                    currentDir
                }
            }
        }

        when (moduleName) {
            null -> {
                val input = prompt("Human readable name for your module (Example - Arduino Driver): ")
                moduleName = input
            }
        }

        when (packageRoot) {
            null -> {
                var input = prompt("Root package to use for all scopes (Example - org.example.driver.arduino): ")
                if (input.endsWith(".")) {
                    input = input.substring(0, input.length - 1)
                }

                packageRoot = input
            }
        }

        log.debug("CLI configuration: ${toString()} ")

        val parent = if (directory == null || directory!!.isEmpty()) {
            File("").toPath()
        } else {
            File(directory!!).toPath()
        }

        val configBuilder = GeneratorConfigBuilder().moduleName(moduleName)
                .parentDir(parent)
                .scopes(scope!!.toCharArray().distinct().joinToString(""))
                .packageName(packageRoot)

        if (localDev) {
            configBuilder.debugPluginConfig(true)
            configBuilder.rootPluginConfig("   id('io.ia.sdk.gradle.modl') version('0.0.1-PREVIEW.1')")
        }

        val config = configBuilder.build()

        log.debug("Assembling module structure from config $config...")
        val initial = Instant.now()
        val projectDir = ModuleGenerator.generate(config)
        val finish = Instant.now()
        log.info("Project has been assembled in $projectDir, created in ${Duration.between(initial, finish).toMillis()}ms")

        return 0
    }

    override fun toString(): String {
        return "Config { name: $moduleName, dir: $directory, scope: $scope, package: $packageRoot }"
    }

    companion object {
        val log: Logger = LoggerFactory.getLogger(ModuleGeneratorCli::class.java)

        @JvmStatic
        fun main(args: Array<String>) {
            System.exit(CommandLine(ModuleGeneratorCli()).execute(*args))
        }
    }
}
