/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.ia.sdk.tools.module.cli

import kotlin.test.Test
import kotlin.test.assertNotNull

class ModuleGeneratorCliTest {
    @Test
    fun `test app initializes class without error`() {
        val classUnderTest = ModuleGeneratorCli()
        assertNotNull(classUnderTest, "app should have a scope")
    }
}
