# This workflow executes upon an merge into master, resulting in a build and (upon success) the publication of a new
# release based on the merge.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release
#  if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.11'
          architecture: x64
      - name: Grant execute permission for generator gradlew
        working-directory: ./generator
        run: chmod +x gradlew
      - name: Gradle Generator Build Task
        working-directory: ./generator
        run: ./gradlew build --stacktrace --info
      - name: Grant execute permission for module plugin gradlew
        working-directory: ./gradle-module-plugin
        run: chmod +x gradlew
      - name: Gradle Module Plugin Build Task
        working-directory: ./gradle-module-plugin
        run: ./gradlew build --stacktrace --info
      - name: Publish Plugins
        working-directory: ./gradle-module-plugin
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{secrets.PLUGIN_PUBLISHING_KEY}} -Pgradle.publish.secret=${{secrets.PLUGIN_PUBLISHING_SECRET}}
